function [fitresult, gof] = createFit(H, R)
%CREATEFIT(H,R)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input : H
%      Y Output: R
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Nov-2016 17:02:32


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( H, R );
Hr=1774;
delta_H=70;
k1=-962007.8274;

% Set up fittype and options.
ft = fittype( 'k1*(4*(x-Hr))/(delta_H^2+4*(x-Hr)^2)^2+k2*((delta_H^2-4*(x-                      Hr)^2)/(delta_H^2+4*(x-Hr)^2)^2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf];
opts.StartPoint = [0.0461713906311539];
opts.Upper = [Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult, xData, yData );
legend( h, 'R vs. H', 'untitled fit 2', 'Location', 'NorthEast' );
% Label axes
xlabel H
ylabel R
grid on


